### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by dadaer** [Elanmarkowitz/StATIK#4]
Hi,I'm very intersted in your work and I'd like to run your code to further understand your work.However,I'm having trouble creating  a conda env.So would you please tell us how to run the code or provide a requirement.txt?

**Comment by dadaer** [comment]
I have figured out this problem.Another problem is the following error when I run train.py
"
  File "train.py", line 189, in train
    loss = loss_fn(pos_scores, neg_scores, neg_filter=neg_filter)
  File "/home/jdl/StATIK-main/model/kg_completion_gnn.py", line 330, in combo_loss
    bce_loss = self.bce_with_logits(mlp_scores[0], mlp_scores[1], neg_filter=neg_filter)
  File "/home/jdl/StATIK-main/model/kg_completion_gnn.py", line 321, in bce_with_logits
    bce_loss = self.bce_with_logits(mlp_scores[0], mlp_scores[1], neg_filter=neg_filter)
File "/home/jdl/StATIK-main/model/kg_completion_gnn.py", line 321, in bce_with_logits
    pos_scores = pos_scores.flatten()[neg_filter.flatten()]
IndexError: The shape of the mask [40200] at index 0 does not match the shape of the indexed tensor [200] at index 0
"
the shape of pos_scores is [200,1], but which of neg_filter is [200, 201]. So this error occured.
Do you write this line of code by mistake? Or could you please tell me how to fix it.

**Comment by dadaer** [comment]
one more...
"
  File "/home/jdl/StATIK-main/evaluation.py", line 9, in compute_eval_stats
    better_than_correct_indices = target_scores > pos_scores.reshape(-1, 1)
ValueError: operands could not be broadcast together with shapes (10000,11633,1) (10000,1) 
"

**Comment by Elanmarkowitz** [comment]
I'll take a look at these and get back to you. And update the README with a requirements.txt

**Comment by dadaer** [comment]
Hi,sorry to bother you again, have you figured out what the problem is?

**Comment by dadaer** [comment]
Hi，thanks for your effort.I hava rerun the project with new code. Problems have been addressed!
