### ISSUE TITLE
[Paper] Inference phase clarification

### ISSUE THREAD

**Issue by AndreiCComan** [Elanmarkowitz/StATIK#5]
Dear authors,

many thanks for putting together such an interesting piece of work! I would like to ask a small, perhaps trivial, clarification regarding the inference phase.

- It is not clear to me whether the MPNN component of your model is being used during the inference phase. If it is the case, how are the neighbors sampled, and with which criterion?

- Is the MPNN just part of the training objective to learn better textual representations and then only the PLM textual encoder output is used as input to the Decoder?

Best regards,
Andrei

**Comment by Elanmarkowitz** [comment]
Hi Andrei, 

Thanks for the questions and interest. 

The MPNN is a core part of the model and used at inference time along with the fine-tuned PLM. The frozen PLM is used for initializing entity representations of neighbor nodes in the MPNN. 

Sampling of neighbors is done uniformly over the edges at both training time (sampling from the training time graph) and at inference time (sampling from the inference time graph). There are most likely smarter approaches such as sampling by relation type to ensure better overall coverage, but that is not done here. 

Doing inference in practice is simpler than when doing evaluation. 

Inference in practice: 
1) Run StATIK encoder over all nodes in graph to get 'targets' (StATIK embeddings for each entity)
  - tokenize node text
  - sample neighborhood of node
  - run through StATIK encoder
2) For each query (e, r, ?) or (?, r, e), run StATIK and compute the scoring function wrt all targets. 
  - tokenize query text
  - sample neighborhood of anchor node (e)
  - run through StATIK encoder
3) Apply scoring function against target embeddings

For evaluation there are some extra steps to ensure data isn't leaked
1) Run StATIK encoder over all nodes in graph to get 'targets' (StATIK embeddings for each entity)
  - tokenize node text
  - sample neighborhood of node
  - run through StATIK encoder
2) For each eval edge (e, r, ?)->true_target or (?, r, e)->true_target, run StATIK on both the query and true_target 
  - tokenize query text
  - sample neighborhood of anchor node (e)
      - filter out the query edge (also done during training)
  - tokenize true_target text
  - sample neighborhood of true_target
      - also filtering out the query edge
  - run queries and true targets through StATIK encoder
3) Apply scoring function for each query against true_targets to get the positive_scores
4) Apply scoring function for each query against `targets` to get negative scores, filtering out any edges that are in the train/validation/test graph (including the current eval edge)

Hope that answered your questions.

Best,
Elan

**Comment by AndreiCComan** [comment]
Hi Elan,

Thank you very much for your prompt reply and for taking the time to write such a thorough and complete clarification!

Best,
Andrei
